### ISSUE TITLE
'type' is not in Demo...

### ISSUE THREAD

**Issue by billmi** [elastic/elasticsearch-php#1040] opened 2020-06-10 05:48 UTC
The field of 'type' is not in Demo...

**Comment by ezimuel** [comment] 2020-06-16 12:25
@billmi what do you mean? Can you give me more context? Thanks.

**Comment by billmi** [comment] 2020-06-17 02:28
> @billmi what do you mean? Can you give me more context? Thanks.

 $params = [
        'index' => 'my_index1',
        'type' => 'novel',
        'id' => $i,
        'body' => [
            'id' => $i,
            'word_count' => $i,
            'author' => "bill" . $i,
            'title' => "bill_abc" . $i,
            'publish_date' => date("Y-m-d H:i:s", time() + (3600 * $i)),
        ]
    ];

**Comment by ezimuel** [comment] 2020-07-17 10:19
@billmi I'm sorry but I don't know where you get this code example. I cannot find it in the repository. I'm closing this since I cannot reproduce the issue. If you will send more information I can reopen it. Thanks.

**Closed by ezimuel** 2020-07-17 10:19 UTC
