### ISSUE TITLE
How to set the timeout to 100 milliseconds?

### ISSUE THREAD

**Issue by Jinnrry** [elastic/elasticsearch-php#1202] opened 2022-03-09 09:45 UTC
### Summary of problem or feature request

I need set the timeout to 100 milliseconds.

### Code snippet of problem

```php
     $params = [
            'index'  => "index",
            'client' => [
                'timeout'         => 100,  // 100 seconds timeout, but I need to set timeout to 100 milliseconds.
                'connect_timeout' => 100,  // 100 seconds connect timeout
            ],
```

### System details

- Operating System: Centos 7
- PHP Version:7.1
- ES-PHP client version:6.0
- Elasticsearch version:6.6.1

**Comment by ezimuel** [comment] 2022-03-25 09:14
@Jinnrry did you try setting `timeout` to `0.1` sec (that is 100 milliseconds)?

**Comment by Jinnrry** [comment] 2022-03-28 03:58
Yes, it should be set to 0.1. The logic of its code is [here](https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L421)

But !!!

Maybe it not work! This is a php curl bug.  [Look Here](https://stackoverflow.com/questions/2582057/setting-curls-timeout-in-php)

If it not work , You should add `curl_setopt($ch, CURLOPT_NOSIGNAL, 1);`

**Comment by ezimuel** [comment] 2022-03-28 08:01
Thanks @Jinnrry as you mentioned there is this [issue](https://www.php.net/manual/en/function.curl-setopt.php#104597) that we need to check. We need to verify that the issue is still relevant, since this comment was about 10 years ago. Did you try to set to `0.1` sec?

**Comment by Jinnrry** [comment] 2022-03-28 09:27
Yes, But it not work. This is a bug in php curl, not related to the elasticsearch-php. Maybe in newest php, it will work.

My PHP Version: 7.1

Curl Version Info:     
    [version_number] => 466176
    [version] => 7.29.0
    [ssl_version] => NSS/3.53.1
    [libz_version] => 1.2.7

**Comment by ezimuel** [comment] 2022-04-01 09:13
@Jinnrry I suggesto to update your PHP version, at least `7.4` since the previous versions are not supported anymore. I'm closing this issue but I can reopen in the future. Thanks for reporting this issue and let me know if I can help you further.

**Closed by ezimuel** 2022-04-01 09:13 UTC
Labels: question
