### ISSUE TITLE
Running test more easier with faster response loop

### ISSUE THREAD

**Issue by Tezd** [elastic/elasticsearch-php#421] opened 2016-05-27 04:05 UTC
### Summary of problem or feature request

To run the tests it requires you to bring up elasticsearch instance. 
Add those changes to `elasticsearch.yml`:

```
path.repo: ["/tmp"]
repositories.url.allowed_urls: ["http://*"]
```

Those lines are required for repository and snapshot tests.
Then you will need to run tests:

``` bash
sudo -H -u elasticsearch bash -c "/usr/bin/env php vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml tests"
```

Since elasticsearch repositories in `/tmp` folder wont have write permissions and without cleaning them up later tests will be broken due to repository already exists.

Tests are integration test run through the elasticseach-php library(long response loop) and you cant select which ones you want to run they will run all at once.
Another problem is that in `util/elasticsearch/rest-api-spec/src/main/resources/rest-api-spec/test` not all endpoint are tested (ex. reindex, update_by_query).

Is there specific reason why we need to test endpoint using integration tests from elasticsearch?
### Suggestion

Use api documentation from `util/elasticsearch/rest-api-spec/src/main/resources/rest-api-spec/api` since it is covering all endpoint. Will make current tests unit tests(faster response loop). Still will leave us with running all of them at once. 

To achieve this we will need to expose endpoints built uri and filtered parameters. And then instead of propagating transport to them and calling performRequest, we will call performRequest in client and namespaces based on return from endpoints
Example mock code renderSearch method from Client:

``` php
public function renderSearchTemplate($params = [])
{
        $this->transport->setOptions($params);
        /** @var callback $endpointBuilder */
        $endpointBuilder = $this->endpoints;
        /** @var \Elasticsearch\Endpoints\RenderSearchTemplate $endpoint */
        $endpoint = $endpointBuilder('RenderSearchTemplate');
        $endpoint->accept($params);
        return $this->transport->performRequest(
              $endpoint->getMethod(),
              $endpoint->getUri(),
              $endpoint->getParams(),
              $endpoint->getBody()
        ); 
}
```

Looking forward for your feedback on this suggestion.

**Comment by polyfractal** [comment] 2016-05-27 13:18
> Is there specific reason why we need to test endpoint using integration tests from elasticsearch?

I'll start with this question first.  Basically, this is something all the REST clients have to do: pass the yaml REST integration tests.  It's one of the basic "contracts" that must be upheld.  

We originally started with all clients doing various unit testing on their own, but found that there were inconsistencies in how things were handled, missing parameters, poor handling of responses, etc.

The integration tests help verify that the clients are working as intended against a live ES server, and helps to check against multiple versions.

> Use api documentation from util/elasticsearch/rest-api-spec/src/main/resources/rest-api-spec/api since it is covering all endpoint.

I'm ++ in general getting more unit tests, assuming they are helpful.  Doing this could help ensure we have complete coverage of the API, but it's only a superficial test.  One of the main reasons we built the yaml integration tests was because the REST json spec doesn't specify body components, or response elements.  The yaml tests verify that A) the endpoint can be used correctly, B) the response can be parsed correctly and C) the response contains the correct elements.  

The REST json spec would only check that the endpoint exists -- which I think we should do! -- but it won't replace the integration tests (unfortunately)

Ok, with that out of the way:

> Add those changes to elasticsearch.yml:

You may not have seen it, but there is a utility helper script that I use with travis to download the most recent version, setup the config, etc:  https://github.com/elastic/elasticsearch-php/blob/master/travis/download_and_run_es.sh

> Since elasticsearch repositories in /tmp folder wont have write permissions and without cleaning them up later tests will be broken due to repository already exists.

Hm, I haven't run into this before, but I can see how that's a problem.  Perhaps we could just move the repo location to the location the scripts are running from?

> and you cant select which ones you want to run they will run all at once.

This is a serious limitation, I agree.  It definitely needs to be enhanced.  In fact, that entire test runner is a nightmare of the worst PHP I've ever written.  It should really be burned down to the ground and rewritten, but alas, "it works" and I haven't found time to justify the effort yet.

> Another problem is that in util/elasticsearch/rest-api-spec/src/main/resources/rest-api-spec/test not all endpoint are tested (ex. reindex, update_by_query).

Yeah, this is also a limitation.  Some endpoints aren't tested yet because they take too long to run (e.g. reindex) or there are limitations that prevent it from being easily testable.  And sometimes the ES devs just forget to add new tests.

> Use api documentation from util/elasticsearch/rest-api-spec/src/main/resources/rest-api-spec/api since it is covering all endpoint. Will make current tests unit tests(faster response loop). Still will leave us with running all of them at once.

I'm not sure I follow the implementation you laid out, but I like the idea of automating simple unit tests against the endpoints.  Wouldn't it be easier to just set a mock Transport in the client that fakes the responses?  If we are just testing that the endpoint exists and the whitelist params are effective, the actual response doesn't matter so mocking the Transport would work?

(As noted in the other ticket, I'm out today, will pick this thread back up monday!)

**Comment by Tezd** [comment] 2016-05-30 07:56
Thank you for your answer. 
I see... You are correct about API not specifying results, but if we can look at this from different point of view:  library isn't the one who (really) consumes the result from elasticsearch(it deserializes json but dont care about structure of it). So testing how it builds urls and parameter will be good enough for unit tests, cause we follow contract from API. Of course it wont replace integration tests (since we want to see that responses got deserialized properly). But those tests will provide faster response on whether we messed up whitelist or endpoint url. 

Idea for my implementation of endpoint is that it no longer can send request through transport. Instead it "consumes" parameters does some validation on them and prepares them, then it "pushes" all necessary information for performing request to transport. That way transport is no longer needed to be mocked (propagated from namespaces to endpoints), becomes more generic.

**Comment by polyfractal** [comment] 2016-05-31 20:34
>  So testing how it builds urls and parameter will be good enough for unit tests, cause we follow contract from API. Of course it wont replace integration tests (since we want to see that responses got deserialized properly). But those tests will provide faster response on whether we messed up whitelist or endpoint url.

++, and we can hide the integration tests behind a flag so that it's only run when the developer wants to do a full test (and for Travis).  Would make it easier/faster for external developers to contribute.

> Idea for my implementation of endpoint is that it no longer can send request through transport. Instead it "consumes" parameters does some validation on them and prepares them, then it "pushes" all necessary information for performing request to transport. That way transport is no longer needed to be mocked (propagated from namespaces to endpoints), becomes more generic.

I see, makes sense.  It may make injecting new namespaces/endpoints easier as well, which is something I've been wanting to improve upon.

Since this would be a rather large change, I think it should be targeted at master only for now.  We can backport to 2.0 if desired later, but I'd prefer to backport instead of forward-port.

I'm personally going to be very busy for the next two weeks, but after that I can dive in to helping.

**Comment by SergeyShcherbin** [comment] 2016-06-01 04:22
Ok, will work on it on weekends.

**Comment by polyfractal** [comment] 2016-07-06 21:09
Went ahead and implemented part of this myself, I needed it for simpler/saner namespace injection that I'm working on.

It's not a 100% clean situation yet (e.g. `resultOrFuture()` still lives in the endpoint, which is a bit odd placement considering the refactor).  But it does the job of removing Transport from endpoints, and is something we can iterate on.

Thanks for the idea and pushing me to consider it! :)

**Comment by SergeyShcherbin** [comment] 2016-07-08 03:13
This whole month was crazy packed at work. Failed to do what have promised/requested with this issue. Sorry for that. Hopefully will have time this/next week to improve generation of phpdocs as discussed.

**Comment by polyfractal** [comment] 2016-07-08 03:32
No problem, I know the feeling!  This was my first productive week back in almost a month (vacation then a work trip, then a short week followed by another work trip, followed by a holiday) :)

And no rush or obligation for any contributions/features.  If I need something in short notice I can take care of it myself, if not, I'll be pleasantly surprised if/when a PR is eventually submitted :)

**Comment by polyfractal** [comment] 2017-03-02 17:47
Closing, a number of these changes were implemented in some fashion in the 5.x branch.

**Closed by polyfractal** 2017-03-02 17:47 UTC
