### ISSUE TITLE
Laravel-Elasticsearch: index_not_found_exception

### ISSUE THREAD

**Issue by bulkerke** [elastic/elasticsearch-php#839] opened 2019-02-22 10:23 UTC
I'm working on a cloned Laravel project that uses 2 languages. When accessing the page in de language, it works. But when accessing with EN, it gives an index_not_found_exception.. I'm very new in Laravel en ES and need to work with this project..

Log file:

```
[local.ERROR: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"ah_index_dev2_en","index_uuid":"_na_","index":"ah_index_dev2_en"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"ah_index_dev2_en","index_uuid":"_na_","index":"ah_index_dev2_en"},"status":404} {"userId":2359,"email":"steven.gerrits.94@gmail.com","exception":"[object] (Elasticsearch\\Common\\Exceptions\\Missing404Exception(code: 404): {\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"ah_index_dev2_en\",\"index_uuid\":\"_na_\",\"index\":\"ah_index_dev2_en\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"ah_index_dev2_en\",\"index_uuid\":\"_na_\",\"index\":\"ah_index_dev2_en\"},\"status\":404} at /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:602)
[stacktrace]
#0 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(273): Elasticsearch\\Connections\\Connection->process4xxError(Array, Array, Array)
#1 /Users/stevengerrits/ah-website/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)
#2 /Users/stevengerrits/ah-website/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /Users/stevengerrits/ah-website/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(294): GuzzleHttp\\Ring\\Core::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))
#5 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array, Object(Elasticsearch\\Connections\\Connection), Object(Elasticsearch\\Transport), Array)
#6 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\\Connections\\Connection->performRequest('GET', '/ah_index_dev2_...', Array, '{\"query\":{\"quer...', Array, Object(Elasticsearch\\Transport))
#7 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1578): Elasticsearch\\Transport->performRequest('GET', '/ah_index_dev2_...', Array, Array, Array)
#8 /Users/stevengerrits/ah-website/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(952): Elasticsearch\\Client->performRequest(Object(Elasticsearch\\Endpoints\\Search))
#9 [internal function]: Elasticsearch\\Client->search(Array)
#10 /Users/stevengerrits/ah-website/vendor/cviebrock/laravel-elasticsearch/src/Manager.php(133): call_user_func_array(Array, Array)
#11 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Cviebrock\\LaravelElasticsearch\\Manager->__call('search', Array)
#12 /Users/stevengerrits/ah-website/app/Service/ElasticSearchService.php(450): Illuminate\\Support\\Facades\\Facade::__callStatic('search', Array)
#13 /Users/stevengerrits/ah-website/app/Http/Controllers/SearchController.php(556): App\\Service\\ElasticSearchService->simpleSearch()
#14 /Users/stevengerrits/ah-website/app/Http/Controllers/SearchController.php(434): App\\Http\\Controllers\\SearchController->doSearch()
#15 [internal function]: App\\Http\\Controllers\\SearchController->horseSearch(Object(Illuminate\\Http\\Request), NULL, 'horse')
#16 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#17 /Users/stevengerrits/ah-website/app/Http/Controllers/Controller.php(30): Illuminate\\Routing\\Controller->callAction('horseSearch', Array)
#18 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): App\\Http\\Controllers\\Controller->callAction('horseSearch', Array)
#19 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SearchController), 'horseSearch')
#20 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#21 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#22 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/stevengerrits/ah-website/app/Http/Middleware/Language.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Language->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/stevengerrits/ah-website/app/Http/Middleware/LanguageSetting.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LanguageSetting->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#50 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#51 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#52 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#53 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/stevengerrits/ah-website/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/stevengerrits/ah-website/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#74 /Users/stevengerrits/ah-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#75 /Users/stevengerrits/ah-website/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#76 /Users/stevengerrits/ah-website/server.php(21): require_once('/Users/stevenge...')
#77 {main}
"} 
```
](url)

ElasticSearch:

curl -XGET localhost:9200/
```
{
  "name" : "Hfe5NY6",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "jDUNRES3SuC5bhUesVpNnw",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}


```

- Mac osx
- PHP 7.1
- Laravel 5.5
- ES 5.4

**Comment by Skill-Zozo** [comment] 2019-07-09 08:21
Hi,

You can check if your index exists using [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html). If a 404 is returned then that index DNE. I ran into the same issue, turns out my ES client was configured to point to some remote server and not `localhost:9200`

**Comment by ezimuel** [comment] 2019-09-03 09:55
@bulkerke I cannot reproduce the issue, you need to provide a working example code. Anyway, did you try the suggestion of @Skill-Zozo? I'm closing this issue. I'll reopen if needed.

**Closed by ezimuel** 2019-09-03 09:55 UTC
