### ISSUE TITLE
index creation issue

### ISSUE THREAD

**Issue by manutic** [elastic/elasticsearch-php#391] opened 2016-02-19 09:50 UTC
Hello,

the following php script issue a PHP Fatal error :

- PHP version : PHP 5.5.9-1ubuntu4.14
- ES version : 2.2.0

```php
<?php

require_once 'vendor/autoload.php';

$es = Elasticsearch\ClientBuilder::create()->build();

$params = [
    'index' => 'my_index',
    'body' => [
        'settings' => [
            'number_of_shards' => 3,
            'number_of_replicas' => 2
        ],
        'mappings' => [
            'my_type' => [
                '_source' => [
                    'enabled' => true
                ],
                'properties' => [
                    'first_name' => [
                        'type' => 'string',
                        'analyzer' => 'standard'
                    ],
                    'age' => [
                        'type' => 'integer'
                    ]
                ]
            ]
        ]
    ]
];

if ( !$es->indices()->exists($params) ) {
    $result = $es->indices()->create($params);
    print_r($result);
}
?>
```
Here is the error log :
`PHP Fatal error:  Uncaught exception 'Elasticsearch\\Common\\Exceptions\\UnexpectedValueException' with message '"body" is not a valid parameter. Allowed parameters are: "ignore_unavailable", "allow_no_indices", "expand_wildcards", "local", "client", "custom", "filter_path"' in /var/www/nutri/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:245\nStack trace:\n#0 /var/www/nutri/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(97): Elasticsearch\\Endpoints\\AbstractEndpoint->checkUserParams(Array)\n#1 /var/www/nutri/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(36): Elasticsearch\\Endpoints\\AbstractEndpoint->setParams(Array)\n#2 /var/www/nutri/build.php(33): Elasticsearch\\Namespaces\\IndicesNamespace->exists(Array)\n#3 {main}\n  thrown in /var/www/nutri/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php on line 245`

Any idea on what could cause this ?

**Comment by polyfractal** [comment] 2016-02-21 21:56
Sorry for the delay, been traveling for work.

I believe the issue is the `exists` API call.  The Exists API doesn't have a request body -- it's just a HEAD request to a URL.  But because your `$params` variable has a body, it's throwing an exception.

If you add the body after calling `exists`, I believe it'll work.

**Comment by polyfractal** [comment] 2016-03-15 15:34
Closing for staleness, but please feel free to reopen if you can provide some more information.

**Closed by polyfractal** 2016-03-15 15:34 UTC
