### ISSUE TITLE
ElasticSearch 2.3.2 single node process dying

### ISSUE THREAD

**Issue by dlapointeus** [elastic/elasticsearch-php#457] opened 2016-08-25 17:05 UTC
### Summary of problem or feature request

First, I read on the discuss.elastic that it was ok to post issues here - if I read that wrong or it's not the case, my apologies and please move this over there.  2 years ago we inherited (through an acquisition) a small Elastic infrastructure for search - 1 node running just a couple of indexes.  It was version 1.5.x.  and we use the PHP client.  It ran with very little attention, and no problems.  We recently have upgraded to version 2.3.2 (client as well), and all seems to work as expected - with the exception that every couple of days the elasticsearch process will die and have to be re-started.  

We've gone through the standard configurations - have bumped up the # of file descriptors (65535), configured the virtual memory (vm.max_map_count=262144), and disabled swap (both swapoff -a and vm.swappiness=0).  

On startup, we've noticed a JNA exception:

unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-2117728981/jna5056863219169361890.tmp: /tmp/jna-2117728981/jna5056863219169361890.tmp: failed to map segment from shared object: Operation not permitted

and also have noticed that we still get a warning about the file descriptors (it shows both the current value and recommended value being the same), although checking node stats does in fact show the higher amount available:

max file descriptors [65536] for elasticsearch process likely too low, consider increasing to at least [65536]

{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "-yVJajvGTpGo3inrhg0t3Q" : {
      "timestamp" : 1472143977249,
      "name" : "Hindsight Lad",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : [ "127.0.0.1:9300", "NONE" ],
      "process" : {
        "timestamp" : 1472143977249,
        "open_file_descriptors" : 381,
        "max_file_descriptors" : 65535,
        "cpu" : {
          "percent" : 1,
          "total_in_millis" : 35280
        },
        "mem" : {
          "total_virtual_in_bytes" : 2628984832
        }
      }
    }
  }
}

The only other thing we've noticed in the logs in that there are continual warnings about high and low disk watermarks being exceeded.  The console at startup is as follows:

[2016-08-25 12:42:57,045][WARN ][bootstrap                ] cannot check if running as root because JNA is not available
[2016-08-25 12:42:57,045][WARN ][bootstrap                ] cannot install syscall filters because JNA is not available
[2016-08-25 12:42:57,047][WARN ][bootstrap                ] cannot register console handler because JNA is not available
[2016-08-25 12:42:58,305][INFO ][node                     ] [Hindsight Lad] version[2.3.2], pid[12468], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-08-25 12:42:58,305][INFO ][node                     ] [Hindsight Lad] initializing ...
[2016-08-25 12:43:01,563][INFO ][plugins                  ] [Hindsight Lad] modules [lang-groovy, reindex, lang-expression], plugins [], sites []
[2016-08-25 12:43:01,757][INFO ][env                      ] [Hindsight Lad] using [1] data paths, mounts [[/ (/dev/sda3)]], net usable_space [25.3gb], net total_space [116.6gb], spins? [possibly], types [ext4]
[2016-08-25 12:43:01,758][INFO ][env                      ] [Hindsight Lad] heap size [1007.3mb], compressed ordinary object pointers [true]
[2016-08-25 12:43:01,758][WARN ][env                      ] [Hindsight Lad] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-08-25 12:43:08,990][INFO ][node                     ] [Hindsight Lad] initialized
[2016-08-25 12:43:08,991][INFO ][node                     ] [Hindsight Lad] starting ...
[2016-08-25 12:43:09,339][INFO ][transport                ] [Hindsight Lad] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2016-08-25 12:43:09,351][INFO ][discovery                ] [Hindsight Lad] elasticsearch/-yVJajvGTpGo3inrhg0t3Q
[2016-08-25 12:43:12,445][INFO ][cluster.service          ] [Hindsight Lad] new_master {Hindsight Lad}{-yVJajvGTpGo3inrhg0t3Q}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-08-25 12:43:12,473][INFO ][http                     ] [Hindsight Lad] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2016-08-25 12:43:12,474][INFO ][node                     ] [Hindsight Lad] started
[2016-08-25 12:43:12,898][INFO ][gateway                  ] [Hindsight Lad] recovered [6] indices into cluster_state
[2016-08-25 12:43:17,567][INFO ][cluster.routing.allocation] [Hindsight Lad] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[alexandria][0]] ...]).

Realize this is probably not enough details for any meaningful diagnosis, however wanted to ask in the event there are some obvious things we should be looking for in 2.3.2 if the process dies again, or if there is additional info we might want to look at when troubleshooting.

Thanks in advance for any help/insight/suggestions!

### System details

- CentOS release 6.8.8 (final)
- PHP Version 5.4.24
- ES-PHP client version:  2.0
- Elasticsearch version: 2.3.2

**Comment by polyfractal** [comment] 2016-08-25 19:48
I generally try to keep issues here related to the PHP client itself, but we can take a quick stab at it.  If we don't figure it out quickly, it'd be best to cross-post to the forums for more eyeballs.

> We've gone through the standard configurations - have bumped up the # of file descriptors (65535)
> and also have noticed that we still get a warning about the file descriptors (it shows both the current value and recommended value being the same), although checking node stats does in fact show the higher amount available:

The error message here is a bit deceiving (there's a bugfix for that in 5.0, iirc).  It really wants the file descriptors to be >= 65536. 

> The only other thing we've noticed in the logs in that there are continual warnings about high and low disk watermarks being exceeded. 

These are generally fine, so long as you actually have enough disk space for regular operation.  You [can configure the watermarks](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html) so they stop making noise, if the amount of available space is expected.

If you *are* running out of disk space, that can make things go pear shaped pretty quickly.  Things can get unpredictable if it runs out of disk space

> unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-2117728981/jna5056863219169361890.tmp: /tmp/jna-2117728981/jna5056863219169361890.tmp: failed to map segment from shared object: Operation not permitted

This is likely caused by a permission's issue related.  Does the user running Elasticsearch have read/write permissions to `/tmp`?  

Is your CentOS locked down with SELinux?  If yes, you may want to work through this ticket which has a similar issue: https://github.com/elastic/elasticsearch/issues/18272  You may need to fiddle with SELinux, or change the tmp path using `-Djna.tmpdir=/path/to/tmp`

Are there any logs from around the time of the crash?  We would need to determine if it's a crash due to something runtime related (e.g ran out of memory, slow GCs, etc) or because of something like a segv due to JNA problems.  Does your node run at high memory pressure?

**Comment by dlapointeus** [comment] 2016-08-26 19:41
Thanks so much for the quick response.  We disabled SELinux and mounted the tmp directory without noexec, and now things start up cleanly.  We have not had an issue since.  We do have ample disk space, and it doesn't appear there is any stress on the memory.  If the process does die in the future, are there any specific log files other than those in the Elastic logs directory that we should be looking at (or are there log settings that we should be applying to get more verbose info)? 

Thanks again for the help.

**Comment by polyfractal** [comment] 2016-08-26 19:50
Np, happy to help :)

Hard to say regarding future problems, depends on what the root cause is.  If it's memory related, you'll see slow GC warnings in the log and eventually an OutOfMemoryException which is pretty easy to spot.

If there's some kind of hard crash, you'll usually see some kind of fault message generated by the JVM, and potentially a heapdump.  You'll likely see something in the system logs too.

Any kind of catastrophic crash would be reported at the default level (INFO), so no need to drop it lower to DEBUG or TRACE.

**Comment by polyfractal** [comment] 2016-10-25 15:56
Closing! :)

**Closed by polyfractal** 2016-10-25 15:56 UTC
