### ISSUE TITLE
Search request with body is missing transfer-encoding or content-length

### ISSUE THREAD

**Issue by zerkms** [elastic/elasticsearch-php#846] opened 2019-03-06 02:59 UTC
### Summary of problem or feature request

It was raised before https://github.com/elastic/elasticsearch-php/issues/737 but closed without further discussion.

It is indeed allowed to send body with GET method.

The problem is that as long as you provide one you must then specify either `Content-Length` or `Transfer-Encoding` or both (https://tools.ietf.org/html/rfc7230#section-3.3)

None of those are provided.

So as expected proxies go crazy, since then there is no way to infer the body length, hence return HTTP 411

### System details

- Operating System N/A
- PHP Version N/A
- ES-PHP client version 6.1.0
- Elasticsearch version N/A

**Comment by ezimuel** [comment] 2019-07-18 15:23
The issue is that for some endpoint we used `GET` instead of `POST` also if the body was not empty. I fixed this and released with [5.5.0](https://github.com/elastic/elasticsearch-php/releases/tag/v5.5.0).
I'm going to release the fix also for 6.1.1, 6.5.1 and 6.7.2. The 7.0 branch should not be affected by the issue, since I generated the code from the Elasticsearch API specifications.

**Closed** 2019-09-03 10:14 UTC
