### ISSUE TITLE
Scan and Scroll : URI length exceeds the configured limit 

### ISSUE THREAD

**Issue by shabbirkc** [elastic/elasticsearch-php#355] opened 2015-12-23 10:10 UTC
I am using scan and scroll functionality for iterating through documents with version 2.1. 
below is how my code looks like
$params = [
    "search_type" => "scan",    // use search_type=scan
    "scroll" => "30s",          // how long between scroll requests. should be small!
    "size" => 50,               // how many results *per shard* you want back
    "index" => "my_index",
    "body" => [multiple_params_here]
    ]
];

$docs = $client->search($params);   // Execute the search
$scroll_id = $docs['_scroll_id'];   // The response will contain no results, just a _scroll_id

while (\true) {

    $response = $client->scroll([
            "scroll_id" => $scroll_id,  //...using our previously obtained _scroll_id
            "scroll" => "30s"           // and the same timeout window
        ]
    );

    if (count($response['hits']['hits']) > 0) {
         foreach ($response['hits']['hits'] as $hit) {
            //doing some activity here
         }
        $scroll_id = $response['_scroll_id'];
    } else {
        break;
    }
}

when i run this code, it shows error URI length exceeds the configured limit of 8192 characters

**Comment by nik9000** [comment] 2015-12-23 14:57
More here:
https://discuss.elastic.co/t/scan-and-scroll-uri-length-exceeds-the-configured-limit/37851/3

Looks like you can work around it but it'd be nice if the client worked around it automatically. It could just do a POST by default.

**Comment by shabbirkc** [comment] 2015-12-24 06:21
Yes Agree. Above solution worked for me. Bu there should be automated way or parameter to use POST instead of get

**Comment by polyfractal** [comment] 2015-12-24 13:39
Also related: https://github.com/elastic/elasticsearch-php/pull/328#issuecomment-161381311

Agreed the client needs to deal with this internally.  The problem is that in ES 1.x used a bare scroll_id in the POST body, while 2.x has a structured JSON body which isn't compatible with 1.x.  

When I'm back from the holidays, I'll talk with the other client devs and figure out how to tackle this.  I'd prefer to keep the client compatible across versions for as long as possible... no one likes to juggle version matrices depending on ES version. :)

**Comment by polyfractal** [comment] 2016-01-04 20:32
Just chatted with the other client devs, apparently ES still accepts a bare scroll_id in the body and maintains bwc.  I'm going to reopen #328 so we can get this fixed!

**Comment by polyfractal** [comment] 2016-01-11 15:35
#361 (successor to #328) was merged, so this should now be fixed!

**Closed by polyfractal** 2016-01-11 15:35 UTC
Labels: bug
