### ISSUE TITLE
This library drains memory like man drinking water in a desert

### ISSUE THREAD

**Issue by guilhermeblanco** [elastic/elasticsearch-php#274] opened 2015-08-05 22:38 UTC
Using simplest configuration possible and calling create() for example 100 times consumes more than 30MB of RAM. Same happens for other operations too, but focusing on one may fix the others.

Writing a console command that reads from RabbitMQ and sends to ElasticSearch using this library makes VM unavailable in ~15-30 seconds by being unable to allocate memory (takes up to 8GB of RAM in my case).

**Comment by polyfractal** [comment] 2015-08-05 23:42
Very poetic ticket title :)

How are you measuring memory usage?

Can you gist up your code?  It's likely that are accidentally appending to the request body each iteration, or not freeing a result array or something similar. 

For example, this demo code behaves just fine:

```php
$client = new Elasticsearch\Client();

for ($i = 0; $i < 100; $i++) {
    $request = [
        'index' => 'test',
        'type' => 'test',
        'body' => [
            'foo' => 'bar'
        ]
    ];
    $client->create($request);
}

$mallocUsage = memory_get_peak_usage(true) / 1024 / 1024;
$internalUsage = memory_get_peak_usage(false) / 1024 / 1024;

echo "Malloc'd memory: $mallocUsage mb\n";
echo "Internally allocated memory: $internalUsage mb\n";
```

```
Malloc'd memory: 6.75 mb
Internally allocated memory: 6.3193359375 mb
```

**Comment by polyfractal** [comment] 2015-08-05 23:47
Another possibility, are you using an alternate logging handler, like `FingersCrossed`?  That is [known to cause problems](https://github.com/elastic/elasticsearch-php/issues/204#issuecomment-91278706) if it isn't configured correctly, since it basically queues log messages forever.

**Comment by polyfractal** [comment] 2015-08-07 00:29
@guilhermeblanco ping?

**Comment by guilhermeblanco** [comment] 2015-08-07 02:24
I've sent you a couple messages on IRC, including an xhprof dump with relevant information. =)

**Comment by polyfractal** [comment] 2015-08-07 02:30
Argh, I think it was lost in the void and/or eaten by my BNC.  Can you attach it here?  If it contains sensitive info, you can email it to me: zach (at) elastic .co

I'll try to catch you on irc if I can

**Comment by polyfractal** [comment] 2015-08-07 18:27
Update:  @guilhermeblanco and I have been doing some debugging over IRC and have generally resolved the situation (for now).  

My notes (guilhermeblanco feel free to correct if I get any of this wrong) :

- The memory concerns are regarding the v2.0 beta branch, not the 1.x branch
- The main memory leak was due to logging.  In dev environments, Symfony injects a TestHandler which basically logs everything at a DEBUG level and stores the log in memory for easy perusal.  The client logs all request/responses at DEBUG, so if you have a long-running process that is indexing a many docs, that can generate a large amount of logs which are staying resident in memory.
- The solution is to not use the `main` Symfony logger, but instead instantiate your own that uses a file stream handler.  You could instead change the verbosity of the `main` logger, but that negatively impacts the rest of your app's logging/debugging
- Once the logging was fixed, the main leak seems to be resolved.  There is/was a potentially a leak potentially caused by cyclic promise references, but we were unable to reproduce the leak.  E.g. virtual memory use grows over time as expected, due to stuff like mmapped files used in file stream handler, but we couldn't get xhprof to reproduce an in-script leak.  Still under investigation
- Alternatively the memory usage may just be memory that hasn't been reclaimed by PHP until it hits the mem limit, at which point it does a full GC.  We could simulate this to a degree by calling manual GCs and did not see the memory continue to climb.

Action points:

- I'm going to add a large warning to the docs about logging and memory usage.  In particular, Symfony's TestHandler will likely trip up new users.  But so will custom-built loggers that use Finger-Crossed.
- I'm doing an audit of the promise handling to make sure there aren't any cycles, as well as reading up on the React issues to see if anyone else has encountered similar.

**Comment by polyfractal** [comment] 2015-08-28 19:27
Closing :)

**Closed by polyfractal** 2015-08-28 19:27 UTC
