### ISSUE TITLE
Update problem in version 6.1: Update API does not work as expected

### ISSUE THREAD

**Issue by masoudjahromi** [elastic/elasticsearch-php#840] opened 2019-02-24 11:10 UTC
in version 6.1, when I want to update the age field, it deletes the other fields in the index and only age field will be remain. this problem doesn't occur in version 6.0.

> my package version: version 6.1

- $endpoint->getURI()

```
/player/player/65152/_update"
```

- $endpoint->getBody()

```
array:1 [▼
  "doc" => array:1 [▼
    "age" => 21
  ]
]
```

```php5
    /**
     * updating a model
     *
     * @param Searchable|BaseModel $model
     */
    public function updated($model)
    {
        if ($model->getDirty()) {
            $partial['doc'] = $model->getDirty();
            $id = $model->getKeyName();
            $this->elasticSearch->update([
                'index' => $model->getSearchIndex(),
                'type'  => $model->getSearchType(),
                'id'    => $model->$id,
                'body'  => $partial,
            ]);
        }
    }
```

**Comment by ezimuel** [comment] 2019-09-20 08:48
@masoudjahromi I was not able to reproduce the issue. Can you send me a simple code (without the Model) to reproduce the issue? You should specify the Elasticsearch version and the elasticsearch-php client version as well, thanks!

**Comment by ezimuel** [comment] 2020-02-14 16:43
@masoudjahromi I'm closing this issue. Let me know if you want to reopen it. Thanks!

**Closed by ezimuel** 2020-02-14 16:43 UTC
Labels: waiting author update
