### ISSUE TITLE
[ERROR] Resource already exists [7.3]

### ISSUE THREAD

**Issue by KaidoRen** [elastic/elasticsearch-php#942] opened 2019-08-26 11:21 UTC
Hello! When I add a new index with mappings and settings, I get the error that index already exists. The problem is that before creating this index I check for its absence - [click](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L41) | [click-2](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L130).

Elasticsearch - 7.3
Elasticsearch PHP Client - 7.2

 ```
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [countries/EnolncXwQe-NXub5J1AtWw] already exists","index_uuid":"EnolncXwQe-NXub5J1AtWw","index":"countries"}],"type":"resource_already_exists_exception","reason":"index [countries/EnolncXwQe-NXub5J1AtWw] already exists","index_uuid":"EnolncXwQe-NXub5J1AtWw","index":"countries"},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"resource_already_exists_exception\",\"reason\":\"index [countries/EnolncXwQe-NXub5J1AtWw] already exists\",\"index_uuid\":\"EnolncXwQe-NXub5J1AtWw\",\"index\":\"countries\"}],\"type\":\"resource_already_exists_exception\",\"reason\":\"index [countries/EnolncXwQe-NXub5J1AtWw] already exists\",\"index_uuid\":\"EnolncXwQe-NXub5J1AtWw\",\"index\":\"countries\"},\"status\":400} at .vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:624)
[stacktrace]

 #0 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(310): Elasticsearch\\Connections\\Connection->process4xxError(Array, Array, Array)
#1 ./vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)
#2 ./vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 ./vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(322): GuzzleHttp\\Ring\\Core::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))
#5 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(220): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array, Object(Elasticsearch\\Connections\\Connection), Object(Elasticsearch\\Transport), Array)
#6 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\\Connections\\Connection->performRequest('PUT', '/countries', Array, '{\"mappings\":{\"p...', Array, Object(Elasticsearch\\Transport))
#7 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php(58): Elasticsearch\\Transport->performRequest('PUT', '/countries', Array, Array, Array)
#8 ./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(864): Elasticsearch\\Namespaces\\AbstractNamespace->performRequest(Object(Elasticsearch\\Endpoints\\Indices\\Create))
#9 ./vendor/kaidoren/elasticquent-lite-search/src/Utils/ElasticsearchUtils.php(70): Elasticsearch\\Namespaces\\IndicesNamespace->create(Array)
#10 ./vendor/kaidoren/elasticquent-lite-search/src/Utils/ElasticsearchUtils.php(44): KaidoRen\\ELSearch\\Utils\\ElasticsearchUtils->createMappings(Object(App\\Country))
```

**Comment by ezimuel** [comment] 2019-08-26 13:55
@KaidoRen it seems you are trying to create an index that already exists but I cannot see how in the log that you reported. Can you give me a working example so I can reproduce the issue? 

Anyway, to create an index with a custom mapping you need to use the code as follows:

```php
$response = $client->indices()->create([
    'index' => 'my-index',
    'body' => [
        "mappings" => [
            "properties" => [
                "my-field" => [ "type" => "my-type" ],
                "my-field2" => [ "type" => "my-type2" ],
                ...
            ]
        ]
    ]
]);
var_dump($response);
/* $response will contains something like that:
array(3) {
  ["acknowledged"]=>
  bool(true)
  ["shards_acknowledged"]=>
  bool(true)
  ["index"]=>
  string(4) "my-index"
}
*/
```
If you want to test if the index already exists:
```php
$response = $client->indices()->exists([
    'index' => 'my-index'
]);
var_dump($response);
/** $response will be true (or false)
bool(true)
```

**Comment by KaidoRen** [comment] 2019-08-26 15:57
@ezimuel Before creating an index, I check its absence. That's why I don't understand why the error appears? I'm doing the right thing, just like you say.

**Comment by ezimuel** [comment] 2019-08-27 12:56
@KaidoRen I tried to reproduce the issue of checking an index before and after it was created but everything is working as expected. If you can give me a working example using your library, I can try to help you more.

**Comment by KaidoRen** [comment] 2019-08-27 13:44
@ezimuel This package was created for Laravel. To reproduce the problem:
**1**. `composer require kaidoren/elasticquent-lite-search`
**2**. add service provider `KaidoRen\ELSearch\ELSearchServiceProvider` to config/app.php
**3**. in model replace the inherited class to KaidoRen\EL Search\SearchableModel (instead of Illuminate\Database\Eloquent\Model). 
**4**. add attribute _**searchableMappings**_ for the model:
```PHP
protected $searchableMappings = [
    'properties' => [
        /*your mappings*/
    ]
]
```
**5**. create a pair of objects in this model so that they are indexed in elasticsearch (there is an observer in the package who is doing the indexing himself)

**Comment by ezimuel** [comment] 2019-08-27 13:55
I just notice this in your `elasticquent-lite-search` code: are you sure that `$params['index']` ([here](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L41)) has the same value of `$params['index']` ([here](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L132)) ?
I guess you are not using the same `index` value when checking and creating the index.

**Comment by KaidoRen** [comment] 2019-08-27 14:22
@ezimuel [click](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L117)

**Comment by ezimuel** [comment] 2019-08-30 08:28
I'm sorry but I cannot reproduce the issue. Anyway, the issue seems to be present in your library and not in `elasticsearch-php` client. 
I'm closing the issue for the moment. If you can send me a complete working example that I can easily install, I'll reopen the issue and try to investigate more.

**Closed by ezimuel** 2019-08-30 08:28 UTC
Labels: waiting author update
